@url = http://localhost:8000 
@reservationId = 00000000-0000-0000-0000-000000000001
@parkingSpotId = 00000000-0000-0000-0000-000000000003

###
GET {{url}}

###
GET {{url}}/parking-spots

###
GET {{url}}/reservations/{{reservationId}}

###
POST {{url}}/parking-spots/{{parkingSpotId}}/reservations/vehicle
Content-Type: application/json

{
    "parkingSpotId": "{{parkingSpotId}}",
    "employeeName": "Ian Doe",
    "licensePlate": "XYABZ10",
    "capacity": 2,
    "date": "2023-11-25"
}

###
POST {{url}}/parking-spots/reservations/cleaning
Content-Type: application/json

{
    "date": "2023-11-25"
}

###
PUT  {{url}}/parking-spots/reservations/{{reservationId}}
Content-Type: application/json

{
    "licensePlate": "XYZR0Z19"
}

###
DELETE {{url}}/parking-spots/reservations/{{reservationId}}
